apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.ports.containerPort }}
      protocol: {{ .Values.ports.protocol }}
  selector:
    app: {{ .Chart.Name }}