server:
  port: 8087

spring:
  application:
    name: data-generator-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      alphanumeric-ids:
        enabled: true

resilience4j.retry:
  configs:
    default:
      maxAttempts: 10
      waitDuration: 100ms
  instances:
    throwingException:
      baseConfig: default
      maxAttempts: 10
      retryExceptions:
        - java.lang.IllegalStateException
        - java.lang.Exception
        - java.lang.Throwable
        - feign.FeignException.BadRequest

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


grpc:
  client:
    dictionary-service-grpc:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiation-type: plaintext
      address: 'discovery:///dictionary-service-grpc'

management:
  server:
    port: 8087
  info:
    os:
      enabled: true
    java:
      enabled: true
  metrics:
    enable:
      tomcat: true
      jvm: true
      process: true
      hikaricp: true
      system: true
      jdbc: true
      logback: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      slo:
        http.server.requests: 1ms, 10ms, 50ms
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    loggers:
      enabled: true
    metrics:
      enabled: true
      distribution:
        slo:
          http:
            server:
              requests: 1ms, 10ms, 50ms
        percentiles-histogram:
          http:
            server:
              requests: true
        percentiles:
          http:
            server:
              requests: 0.5, 0.9, 0.95, 0.99, 0.999
    health:
      show-details: always
  endpoints:
    web:
      exposure:
         include: '*' 
  tracing:
    sampling:
      probability: 1.0
springdoc:
  enable-kotlin: false
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"