apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc
  labels:
    app: postgres-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.requests.memory }}