apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    spring-boot: "true"
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.ports.name }}
      port: {{ .Values.ports.containerPort }}
      targetPort: {{ .Values.ports.targetPort }}
      protocol: {{ .Values.ports.protocol }}
      appProtocol: {{ .Values.ports.appProtocol }}
    - name: "rest"
      port: 8080
      targetPort: 8080
      protocol: TCP
      appProtocol: http

  selector:
    app: {{ .Chart.Name }}