apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-configmap
data:
  datasource.yml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-svc:9090
        basicAuth: false
        isDefault: true
        editable: false
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki-svc:3100
        basicAuth: false
        isDefault: false
        editable: false