image:
  repository: localhost:5001/dictionary_image
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 1Gi

ports:
  name: grpc
  containerPort: 9090
  protocol: TCP
  targetPort: 9090
  appProtocol: TCP

  service: 8080

service:
  type: ClusterIP
  port: 8080

db:
  name: postgres
  host: postgres-db-svc
  port: 5432
  username: postgres
  password: password
  schema: dictionary
