server:
  port: 8085

spring:
  application:
    name: client-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db?currentSchema=client
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/db?currentSchema=client
    password: password
    user: postgres
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui
  enable-kotlin: false

management:
  server:
    port: 8085
  info:
    os:
      enabled: true
    java:
      enabled: true
  metrics:
    enable:
      tomcat: true
      jvm: true
      process: true
      hikaricp: true
      system: true
      jdbc: true
      logback: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      slo:
        http.server.requests: 1ms, 10ms, 50ms
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    loggers:
      enabled: true
    metrics:
      enabled: true
      distribution:
        slo:
          http:
            server:
              requests: 1ms, 10ms, 50ms
        percentiles-histogram:
          http:
            server:
              requests: true
        percentiles:
          http:
            server:
              requests: 0.5, 0.9, 0.95, 0.99, 0.999
    health:
      show-details: always
  endpoints:
    web:
      exposure:
         include: '*'
  tracing:
    sampling:
      probability: 1.0

topic:
  alert:
    risk:
      score: risk.score.notification.v1

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"