apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  {{- (.Files.Glob "config/application.yml").AsConfig | nindent 2 }}
  SPRING_LIQUIBASE_URL: "jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}?currentSchema=contract"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.db.username }}"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}?currentSchema=contract"